import { Box, Text, Divider, Flex } from "@chakra-ui/react";

export default function Copyright() {
    return (
        <Box width="100%" mt={16} fontSize="14px">
            <Divider/>

            <Flex mt={3} mb={8} width="100%" textAlign={{base: "center", md:"start"}} direction={{base: "column", md:"row"}} justifyContent={{ base:"center", md: "space-between"}}>
                <Text color="white" mb={{base: 3, md:0}}>Made in Virginia.</Text>
                <Text color="white">Copyright Reprosify 2024. All rights reserved</Text>
            </Flex>
            
            <Text textAlign={{base: "start", md: "justify"}} color="white" lineHeight={1.6} mb={6}>Disclaimer: All information provided by the listing agent/broker is considered reliable but not guaranteed and should be independently verified. Reprosify.com adheres fully to the principles of the Fair Housing Act and the Equal Opportunity Act. Properties are subject to prior sale, change, or withdrawal. Neither Reprosify, listing broker(s), nor information provider(s) will be held responsible for any typographical errors, misinformation, or misprints and shall be held harmless. Listing information is provided for consumers’ personal, non-commercial use and may not be used for any purpose other than to identify prospective properties consumers may be interested in purchasing.</Text>

            <Text textAlign={{base: "start", md: "justify"}} color="white" lineHeight={1.6} mb={6}>DMCA Notice: Reprosify is committed to safeguarding intellectual property rights and ensuring a respectful online environment. We expect all visitors and users of our services to uphold the same values. In accordance with the Digital Millennium Copyright Act of 1998 (DMCA), Reprosify takes copyright infringement seriously and will take decisive action against any party that infringes upon Reprosify’s services and/or the Reprosify website (referred to as the “Site”).</Text>

            <Text textAlign={{base: "start", md: "justify"}} color="white" lineHeight={1.6} mb={6}>Trademark Disclaimer: All third-party trademarks (including logos and icons) referenced by Reprosify remain the property of their respective owners. Unless specifically identified as such, Reprosify’s use of third-party trademarks does not indicate any relationship, sponsorship, or endorsement between Reprosify and the owners of these trademarks. Any references by Reprosify to third party trademarks are to identify the corresponding third party goods and/or services and shall be considered nominative fair use under the trademark law.</Text>

            <Text textAlign={{base: "start", md: "justify"}} color="white" lineHeight={1.6} mb={6}>Verification Disclaimer: Always verify agent, brokerage, and user information, especially if accuracy is crucial. Reprosify makes extensive efforts to ensure the accuracy of the information; however, there may be instances where the responses and information generated by Reprosify and its AI could be incomplete, inaccurate, or outdated. Users are encouraged to verify information obtained through Reprosify and should not solely rely on it for critical decisions.</Text>
        </Box>
    );
}