import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChakraProvider } from '@chakra-ui/react'
import Footer from "./components/landingPage/footer/index";
import Header from "./components/landingPage/header/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Digilancer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ChakraProvider>
        <Header/>
        <main>{children}</main>
        <Footer/>
      </ChakraProvider>
      </body>
    </html>
  );
}
